### ISSUE TITLE
Document how the dissemination pipeline works

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/indexing-service#2]

**Comment by blankdots** [comment]
Reviewed https://github.com/ATTX-project/ATTX-project.github.io/blob/dev/attx_project/Dissemination-Workflow.md I think we should keep it progress as we develop the services. Our understanding might change on how these should work.
@jkesanie just a wild thought maybe we should have the examples more consistent. You are using "The Republic". I am working on sparse data etc. we should include this in: https://github.com/ATTX-project/ATTX-project.github.io/issues/84

**Comment by blankdots** [comment]
@jkesanie nitpicking:
Figure X -> maybe Figure 1
"associated with the dataset(?)" - why is there a question mark
a bit cleared: Transformation step takes the dataset URIs as an input, and sends them, additionally it also requires as an input the configured/generated mapping tot the FramingService.
